# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: revalyze-ingress
  namespace: revalyze
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 4500
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: revalyze_landing
                port:
                  number: 80
