name: Build and Deploy CMS

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: nickglas/revalyze-cms
      IMAGE_TAG: latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Check required GitHub secrets presence
        run: |
          secrets=(
            "${{ secrets.DOCKERHUB_TOKEN }}"
            "${{ secrets.DOCKERHUB_USERNAME }}"
            "${{ secrets.VPS_HOST }}"
            "${{ secrets.VPS_SSH_KEY }}"
            "${{ secrets.VPS_USER }}"
          )
          secret_names=(
            "DOCKERHUB_TOKEN"
            "DOCKERHUB_USERNAME"
            "VPS_HOST"
            "VPS_SSH_KEY"
            "VPS_USER"
          )
          missing=0
          for i in "${!secrets[@]}"; do
            if [ -z "${secrets[$i]}" ]; then
              echo "::error::Secret ${secret_names[$i]} is NOT set!"
              missing=$((missing+1))
            fi
          done
          if [ $missing -ne 0 ]; then
            echo "Missing $missing required secret(s). Failing workflow."
            exit 1
          else
            echo "All required secrets are set."
          fi

      - name: Build Vite React app
        run: npm run build
        env:
          VITE_API_BASE_URL: "/api"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            if [ ! -d "/home/ubuntu/revalyze_cms/.git" ]; then
              git clone https://github.com/nickglas/revalyze_cms.git /home/ubuntu/revalyze_cms
            else
              cd /home/ubuntu/revalyze_cms && git pull origin main
            fi

            # Apply manifests
            microk8s.kubectl apply -f /home/ubuntu/revalyze_cms/k8s/cms-deployment.yaml
            microk8s.kubectl apply -f /home/ubuntu/revalyze_cms/k8s/cms-service.yaml
            microk8s.kubectl apply -f /home/ubuntu/revalyze_cms/k8s/ingress.yaml

            # Restart CMS
            microk8s.kubectl rollout restart deployment/revalyze-cms -n revalyze
