name: Build and Deploy CMS

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: nickglas/revalyze-cms
      IMAGE_TAG: latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Create namespace if needed
            microk8s.kubectl create namespace revalyze --dry-run=client -o yaml | microk8s.kubectl apply -f -

            # Apply manifests
            microk8s.kubectl apply -f https://raw.githubusercontent.com/nickglas/revalyze_cms/main/k8s/cms-deployment.yaml
            microk8s.kubectl apply -f https://raw.githubusercontent.com/nickglas/revalyze_cms/main/k8s/cms-service.yaml

            # Restart deployment
            microk8s.kubectl rollout restart deployment/revalyze-cms -n revalyze
